### ISSUE TITLE
Request not serialized correctly

### ISSUE THREAD

**Issue by JeffAshton** [building5/sails-hook-bunyan#1]
When creating a child logger, we are passing ( simple: true )

From:  https://github.com/building5/sails-hook-bunyan/blob/master/index.js#L158

``` js
req.log = _this.logger.child({req: req}, true);
```

Reading the documentation in bunyan, for child (https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L584), 
- @param simple {Boolean} Optional. Set to true to assert that `options`
-    (a) only add fields (no config) and (b) no serialization handling is
-    required for them. IOW, this is a fast path for frequent child
-    creation. See 'tools/timechild.js' for numbers.

Passing true fails condition (b) since we want to serialize the request.

Well I can appreciate we want things to be fast, I can't think of a case where we would want to serialize the entire request.  There is way to much crap on the request object otherwise.

**Comment by leedm777** [comment]
@JeffAshtonCT Yikes. I thought the non-serialization for simple children was a bug (and [submitted a PR to "fix" it](https://github.com/trentm/node-bunyan/pull/266)).

> Well I can appreciate we want things to be fast, I can't think of a case where we would want to serialize the entire request.

This wasn't about being fast. The `reopenFileStreams()` call on bunyan causes child loggers to crash if they aren't simple (b/c they don't share the stream objects that are being reopened).

Giving it some more thought, I can run the `req` serializer manually when creating the child logger. That should fix both problems. Thoughts?

**Comment by leedm777** [comment]
Fixed in v2.1.1

**Comment by JeffAshton** [comment]
Looks good. Thanks for fixing.
