### ISSUE TITLE
Empty stdout

### ISSUE THREAD

**Issue by snovak7** [building5/sails-hook-bunyan#8]
I added the module to my project, like so: 

```
npm install sails-hook-bunyan --save
```

but then logging stopped working altogether.

I used it with sails v0.11.1

Tried it with default config/bunyan.js as well as it is on README, didn't help.
Application seems to work, just without any information in my console.

**Comment by leedm777** [comment]
I'll take a look, but you may try downgrading to v0.11.0.

I'm not sure what the story is, but [v0.11.0 is the latest](https://groups.google.com/d/msg/sailsjs/1Fi74H3zw6U/TeJi5NBGl80J), even though there's a v0.11.1 on npm.

**Comment by leedm777** [comment]
@snovak7 I've tried it with both sails 0.11.0 and 0.11.1, and don't have any problems.

``` bash
dlee@dlee-mac:tmp                                                              
$ sails new bunyan
info: Created a new Sails app `bunyan`!
dlee@dlee-mac:tmp                                                              
$ cd bunyan
dlee@dlee-mac:bunyan                                                           
$ npm install --save sails-hook-bunyan

> dtrace-provider@0.5.0 install /Users/dlee/tmp/bunyan/node_modules/sails-hook-bunyan/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

sails-hook-bunyan@2.1.2 node_modules/sails-hook-bunyan
└── bunyan@1.4.0 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.5.0)
dlee@dlee-mac:bunyan                                                           
$ vi config/bootstrap.js 
# add sails.log.info('hi');
dlee@dlee-mac:bunyan                                                           
$ sails lift

info: Starting app...

{"name":"sails","hostname":"dlee-mac","pid":92739,"level":30,"msg":"hi","time":"2015-08-21T12:52:03.783Z","v":0}
```

**Comment by leedm777** [comment]
@snovak7 Some steps you might try in debugging.
1. Are you looking for the sailboat logo? If so, I disable that, because it looks super silly when wrapped up in JSON for bunyan.
2. Add `console.log(sails.hooks.bunyan)` to your bootstrap. Is the bunyan hook is installed? Does `logger` look right? Does `logger._level` look like what you expect?
3. Try several `sails.log.<level>()` for `info`, `warn`, `error`, `crit`, etc. Do any of them work?

**Comment by snovak7** [comment]
So I've checked:
1. Level debug doesn't output anything. I would say that this:
   
   ```
   sails.log('hi');
   ```
   
   is equivalent of
   
   ```
   sails.log.debug('hi');
   ```
2. Level info outputs as expected
3. So what should I do to output debug, I have added in config bunyan.js with 
   
   ``` javascript
   module.exports.bunyan = { 
     level: null
   }
   ```
   
   also I've tried with `level: 'debug'` and nothing happened.

**Comment by snovak7** [comment]
1. I've figured out how to fix it, seems like sails has it's own level configuration, and it's own default, which messes with the bunyan level, and you need to set both to the same level to make it work.
2. I figured proper way to set log level for bunyan
   
   ``` javascript
   module.exports.bunyan = {
     logger: {
       level: 'debug'
     }
   }
   ```

**Comment by leedm777** [comment]
@snovak7 Was about to post about it. I'm fixing the docs now.
